# Generated by Django 5.1.2 on 2024-11-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_phone_number_alter_client_tag'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
    ]
